vector:
  nodeSelector:
    team: devops
    service: devops-infra
    performance_type: standard
  image:
    repository: docker.io/timberio/vector
    version: "0.36.1-distroless-libc"
  persistence:
    enabled: true
  podMonitor:
    enabled: true
  customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false