apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-pgadmin4
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgadmin-pgadmin4
    template:
      data:
        password: "{{ .adminPassword }}"
  data:
  - secretKey: adminPassword
    remoteRef:
      key: pgadmin/admin
      property: password
