apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- externalsecret.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: development
  releaseName: pgadmin
  valuesFile: ./values.yaml