---
- name: Add opentelemetry chart repo
  kubernetes.core.helm_repository:
    name: opentelemetry
    repo_url: https://open-telemetry.github.io/opentelemetry-helm-charts

- name: Install opentelemetry-collector
  kubernetes.core.helm:
    name: opentelemetry-collector
    state: present
    chart_version: 0.77.0
    chart_ref: opentelemetry/opentelemetry-collector
    namespace: "{{ release_namespace }}"
    # create_namespace: true
    update_repo_cache: true
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    kube_context: "{{ cluster_arn }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  register: output

- debug:
    var: output