apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
# - pv.yaml
# - pvc.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: development
  releaseName: nexus
  valuesFile: ./values.yaml