apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus
  labels:
    app: nexus
spec:
  storageClassName: gp3
  volumeName: nexus-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi