apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secretstore.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: provisioning
  releaseName: external-secrets