apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simple
rules:
- verbs:
  - list
  - watch
  apiGroups:
  - ""
  resources:
  - pods
  - namespaces
- verbs:
  - list
  - watch
  apiGroups:
  - apps
  resources:
  - replicasets
- verbs:
  - get
  apiGroups:
  - ""
  resources:
  - configmaps