apiVersion: v2
name: artifact-hub
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: artifact-hub
  version: 1.16.0
  # repository: https://artifacthub.github.io/helm-charts
  repository: https://kwangil77.github.io/helm-charts