artifact-hub:
  pullPolicy: Always
  dynamicResourceNamePrefixEnabled: true
  dbMigrator:
    job:
      nodeSelector:
        team: devops
        service: devops-infra
        performance_type: standard
      image:
        repository: ghcr.io/kwangil77/db-migrator
    loadSampleData: false
  hub:
    deploy:
      nodeSelector:
        team: devops
        service: devops-infra
        performance_type: standard
      image:
        repository: docker.io/artifacthub/hub
      initContainers:
        checkDbMigrator:
          image:
            repository: docker.io/bitnami/kubectl
    server:
      allowPrivateRepositories: true
      allowUserSignUp: false
  scanner:
    cronjob:
      nodeSelector:
        team: devops
        service: devops-infra
        performance_type: standard
      image:
        repository: docker.io/artifacthub/scanner
  tracker:
    cronjob:
      nodeSelector:
        team: devops
        service: devops-infra
        performance_type: standard
      image:
        repository: docker.io/artifacthub/tracker
  trivy:
    deploy:
      nodeSelector:
        team: devops
        service: devops-infra
        performance_type: standard
      image: docker.io/aquasec/trivy:0.43.1
    persistence:
      enabled: true
  postgresql:
    enabled: false
    image:
      registry: docker.io