apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
# - pv.yaml
# - pvc.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: development
  releaseName: jenkins
  valuesFile: ./values.yaml