apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  storageClassName: gp3
  volumeName: jenkins-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi