tempo-distributed:
  fullnameOverride: tempo
  ingester:
    replicas: 1
    extraArgs:
    - -config.expand-env=true
    extraEnvFrom:
    - secretRef:
        name: tempo-env
    config:
      replication_factor: 1
  metricsGenerator:
    config:
      processor:
        service_graphs:
          max_items: 10000
          histogram_buckets:
          - 0.1
          - 0.2
          - 0.4
          - 0.8
          - 1.6
          - 3.2
          - 6.4
          - 12.8
          dimensions:
          - environment
          span_multiplier_key: "X-SampleRatio"
        span_metrics:
          dimensions:
          - environment
          span_multiplier_key: "X-SampleRatio"
      storage:
        remote_write:
        - url: "http://mimir-gateway.observability/api/v1/push"
          send_exemplars: true
  compactor:
    extraArgs:
    - -config.expand-env=true
    extraEnvFrom:
    - secretRef:
        name: tempo-env
    config:
      compaction:
        block_retention: 24h
  querier:
    extraArgs:
    - -config.expand-env=true
    extraEnvFrom:
    - secretRef:
        name: tempo-env
  queryFrontend:
    extraArgs:
    - -config.expand-env=true
    extraEnvFrom:
    - secretRef:
        name: tempo-env
  storage:
    trace:
      backend: s3
      s3:
        bucket: example-dev-tempo-bucket
        endpoint: minio-hl.management:9000
        access_key: ${MINIO_ACCESS_KEY}
        secret_key: ${MINIO_SECRET_KEY}
        insecure: true
        # endpoint: "s3.amazonaws.com"
        # region: ap-northeast-2