vector:
  containerPorts:
  - name: fluent
    containerPort: 24224
    protocol: TCP
  customConfig:
    sources:
      fluent:
        type: fluent
        address: 0.0.0.0:24224
    sinks:
      loki:
        type: loki
        inputs:
        - fluent
        endpoint: "http://loki-distributor.observability:3100"
        labels:
          cluster: example-dev
          namespace: "{{`{{ kubernetes.namespace_name }}`}}"
          node_name: "{{`{{ kubernetes.host }}`}}"
          pod: "{{`{{ kubernetes.pod_name }}`}}"
          container: "{{`{{ kubernetes.container_name }}`}}"
          labels_*: "{{`{{ kubernetes.labels }}`}}"
        encoding:
          codec: json