apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-secret
    template:
      data:
        config.env: |-
          export MINIO_ROOT_USER={{ .accessKey }}
          export MINIO_ROOT_PASSWORD={{ .secretKey }}
  data:
  - secretKey: accessKey
    remoteRef:
      key: minio/secret
      property: access-key
  - secretKey: secretKey
    remoteRef:
      key: minio/secret
      property: secret-key
