apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-system
  labels:
    app: dapr
spec:
  metric:
    enabled: true
  mtls:
    allowedClockSkew: 15m
    enabled: true
    workloadCertTTL: 24h
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: http://grafana-agent.observability:14317
      isSecure: false
      protocol: grpc