apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- podmonitor.yaml
- component.yaml
- configuration.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: management
  releaseName: dapr
  valuesFile: ./values.yaml