apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- ingress.yaml
- operatorcontext.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: management
  releaseName: tyk
  valuesFile: ./values.yaml