apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: management
  releaseName: litmus
  valuesFile: ./values.yaml