apiVersion: v2
name: redis
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: redis
  version: 18.19.2
  repository: https://charts.bitnami.com/bitnami