apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana
    template:
      data:
        admin-user: admin
        admin-password: "{{ .adminPassword }}"
  data:
  - secretKey: adminPassword
    remoteRef:
      key: grafana/admin
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-env
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-env
    template:
      data:
        GF_DATABASE_URL: "postgres://grafana:{{ .dbPassword }}@postgresql-hl.development:5432/grafana"
  data:
  - secretKey: dbPassword
    remoteRef:
      key: grafana/postgresql
      property: password