apiVersion: v2
name: thanos
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: thanos
  version: 14.0.1
  repository: https://charts.bitnami.com/bitnami
- name: memcached
  version: 6.14.0
  repository: https://charts.bitnami.com/bitnami
  alias: memcached-frontend
  condition: memcached-frontend.enabled
- name: memcached
  version: 6.14.0
  repository: https://charts.bitnami.com/bitnami
  alias: memcached-index
  condition: memcached-index.enabled
- name: memcached
  version: 6.14.0
  repository: https://charts.bitnami.com/bitnami
  alias: memcached-bucket
  condition: memcached-bucket.enabled