grafana:
  nodeSelector:
    team: devops
    service: devops-infra
    performance_type: standard
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:...:certificate/...
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/tags: "Team=devops,Server=etc,Service=grafana,Security_level=moderate,Environment=dev"
      alb.ingress.kubernetes.io/healthcheck-path: /api/health
      alb.ingress.kubernetes.io/security-groups: sg-...
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      # nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    hosts:
    - "grafana.example.io"
  service:
    type: NodePort
  grafana.ini:
    server:
      root_url: "https://grafana.example.io"
    database:
      url: "postgres://grafana:<path:kv/data/grafana/postgresql#password>@....ap-northeast-2.rds.amazonaws.com/grafana"
    remote_cache:
      connstr: "addr=....cache.amazonaws.com:6379,pool_size=100,db=1"
    users:
      auto_assign_org_role: Editor
    auth.anonymous:
      enabled: true
      org_name: Example
      org_role: Viewer
    auth.generic_oauth:
      enabled: true
      name: Keycloak
      allow_sign_up: true
      scopes: openid,email,profile,groups
      client_id: grafana
      client_secret: <path:kv/data/grafana/oidc#client-secret>
      auth_url: "https://keycloak.example.io/realms/master/protocol/openid-connect/auth"
      token_url: "https://keycloak.example.io/realms/master/protocol/openid-connect/token"
      api_url: "https://keycloak.example.io/realms/master/protocol/openid-connect/userinfo"
      role_attribute_path: contains(groups[*], 'G_DevOps') && 'Admin' || 'Editor'
  adminPassword: <path:kv/data/grafana/admin#password>
  plugins:
  - grafana-oncall-app
  imageRenderer:
    nodeSelector:
      kubernetes.io/arch: amd64
      team: devops
      service: devops-infra
      performance_type: standard