apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: istio-system
  releaseName: istio-operator
  valuesFile: ./values.yaml