harbor:
  nginx:
    image:
      repository: goharbor/nginx-photon
      tag: "v2.10.0"
  portal:
    nodeSelector:
      kubernetes.io/arch: amd64
      team: devops
      service: devops-infra
      performance_type: memory
    tolerations:
    - key: performance_type
      operator: Equal
      value: mem
      effect: NoSchedule
    image:
      repository: goharbor/harbor-portal
      tag: "v2.10.0"
  core:
    nodeSelector:
      kubernetes.io/arch: amd64
      team: devops
      service: devops-infra
      performance_type: memory
    tolerations:
    - key: performance_type
      operator: Equal
      value: mem
      effect: NoSchedule
    image:
      repository: goharbor/harbor-core
      tag: "v2.10.0"
  jobservice:
    nodeSelector:
      kubernetes.io/arch: amd64
      team: devops
      service: devops-infra
      performance_type: memory
    tolerations:
    - key: performance_type
      operator: Equal
      value: mem
      effect: NoSchedule
    image:
      repository: goharbor/harbor-jobservice
      tag: "v2.10.0"
  registry:
    nodeSelector:
      kubernetes.io/arch: amd64
      team: devops
      service: devops-infra
      performance_type: memory
    tolerations:
    - key: performance_type
      operator: Equal
      value: mem
      effect: NoSchedule
    registry:
      image:
        repository: goharbor/registry-photon
        tag: "v2.10.0"
    controller:
      image:
        repository: goharbor/harbor-registryctl
        tag: "v2.10.0"
  chartmuseum:
    enabled: false
  trivy:
    nodeSelector:
      kubernetes.io/arch: amd64
      team: devops
      service: devops-infra
      performance_type: memory
    tolerations:
    - key: performance_type
      operator: Equal
      value: mem
      effect: NoSchedule
    image:
      repository: goharbor/trivy-adapter-photon
      tag: "v2.10.0"
    replicas: 3
    timeout: 10m0s
    resources:
      limits:
        cpu: 3000m
        memory: 1Gi
  notary:
    enabled: false
  exporter:
    nodeSelector:
      kubernetes.io/arch: amd64
      team: devops
      service: devops-infra
      performance_type: memory
    tolerations:
    - key: performance_type
      operator: Equal
      value: mem
      effect: NoSchedule
    image:
      repository: goharbor/harbor-exporter
      tag: "v2.10.0"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true