apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/VictoriaMetrics/operator/releases/download/v0.34.1/crd.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: observability
  releaseName: victoria-metrics-operator