---
- name: Install crd
  kubernetes.core.k8s:
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    context: "{{ cluster_arn }}"
    state: present
    definition: "{{ lookup('url', 'https://raw.githubusercontent.com/aws/eks-charts/master/stable/aws-load-balancer-controller/crds/crds.yaml', split_lines=false) | from_yaml_all | list }}"
  register: output

- debug:
    var: output

- name: Add eks chart repo
  kubernetes.core.helm_repository:
    name: eks
    repo_url: https://aws.github.io/eks-charts

- name: Install aws-load-balancer-controller
  kubernetes.core.helm:
    name: aws-load-balancer-controller
    state: present
    chart_version: 1.4.0
    chart_ref: eks/aws-load-balancer-controller
    namespace: "{{ release_namespace }}"
    # create_namespace: true
    update_repo_cache: true
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    kube_context: "{{ cluster_arn }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  register: output

- debug:
    var: output 