version: '2'
services:
  app:
    image: ghcr.io/kwangil77/simple-api:${TAG}
    ports:
    - "8080:8080"
    environment:
      TZ: ${TZ}
      JAVA_TOOL_OPTIONS: >
        -Xms256m -Xmx256m
        -Duser.timezone=${TZ}
        -Dspring.profiles.active=${TAG_ENVIRONMENT}
        -javaagent:/pinpoint-agent/pinpoint-bootstrap.jar
        -Dpinpoint.agentId=${INSTANCE_ID}
        -Dpinpoint.applicationName=${TAG_SERVICE}
        -Dmanagement.metrics.export.statsd.host=${IP}
    restart: always
  nginx:
    image: docker.io/library/nginx:1.20
    ports:
    - "80:80"
    environment:
      TZ: ${TZ}
    links:
    - "app"
    volumes:
    - ./.platform/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./.platform/nginx/conf.d:/etc/nginx/conf.d:ro
    - /var/app/resolvers.conf:/etc/nginx/resolvers.conf:ro
    restart: always
