---
- name: Add kiali chart repo
  kubernetes.core.helm_repository:
    name: kiali
    repo_url: https://kiali.org/helm-charts

- name: Install kiali
  kubernetes.core.helm:
    name: kiali
    state: present
    chart_version: 1.81.0
    chart_ref: kiali/kiali-server
    namespace: "{{ release_namespace }}"
    # create_namespace: true
    update_repo_cache: true
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    kube_context: "{{ cluster_arn }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  register: output

- debug:
    var: output