apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  profile: minimal
  components:
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          type: ClusterIP
  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: JSON
    defaultProviders:
      metrics:
      - prometheus
    extensionProviders: 
    - name: opentelemetry
      zipkin:
        service: opentelemetry-collector.observability
        port: 4317
    enableTracing: true
    trustDomain: cluster.local