apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/instance: kong
spec:
  endpoints:
  - targetPort: status
    scheme: http
  - targetPort: cmetrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: kong
      app.kubernetes.io/instance: kong
      enable-metrics: "true"
  namespaceSelector:
    any: true