kong:
  fullnameOverride: kong
  env:
    pg_host: "....ap-northeast-2.rds.amazonaws.com"
    pg_database: "kong"
    pg_password: <path:kv/data/kong/postgresql#password>
    tracing_instrumentations: all
    tracing_sampling_rate: '1.0'
    admin_gui_api_url: https://kong-manager.example.io
    admin_gui_listen: 0.0.0.0:8002, 0.0.0.0:8445 http2 ssl
    admin_gui_url: https://kong-manager.example.io
    admin_gui_path: /manager
  admin:
    enabled: true
    type: ClusterIP
  proxy:
    type: ClusterIP
    http:
      servicePort: 8000
    tls:
      servicePort: 8443
  status:
    tls:
      enabled: true
      parameters:
      - http2
  manager:
    type: ClusterIP
  extraObjects:
  - apiVersion: configuration.konghq.com/v1
    kind: KongClusterPlugin
    metadata:
      name: prometheus
      annotations:
        kubernetes.io/ingress.class: kong
      labels:
        global: "true"
    plugin: prometheus
  - apiVersion: configuration.konghq.com/v1
    kind: KongClusterPlugin
    metadata:
      name: opentelemetry
      annotations:
        kubernetes.io/ingress.class: kong
      labels:
        global: "true"
    config:
      endpoint: http://grafana-agent.observability:14318/v1/traces
    plugin: opentelemetry