apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mimir-env
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mimir-env
    template:
      data:
        MINIO_ACCESS_KEY: "{{ .accessKey }}"
        MINIO_SECRET_KEY: "{{ .secretKey }}"
  data:
  - secretKey: accessKey
    remoteRef:
      key: minio/secret
      property: access-key
  - secretKey: secretKey
    remoteRef:
      key: minio/secret
      property: secret-key