apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kubeclarity
  labels:
    app: kubeclarity
spec:
  podMetricsEndpoints:
  - port: health
  selector:
    matchLabels:
      app: kubeclarity
  namespaceSelector:
    any: true
