apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: management
  releaseName: minio-operator
  valuesFile: ./values.yaml