apiVersion: v2
name: kyverno
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: kyverno
  version: 3.1.4
  repository: https://kyverno.github.io/kyverno