kyverno:
  test:
    image:
      registry: docker.io/library
  admissionController:
    nodeSelector:
      team: devops
      service: devops-infra
      performance_type: standard
    initContainer:
      image:
        registry: ghcr.io
    container:
      image:
        registry: ghcr.io
    serviceMonitor:
      enabled: true
  backgroundController:
    nodeSelector:
      team: devops
      service: devops-infra
      performance_type: standard
    image:
      registry: ghcr.io
    serviceMonitor:
      enabled: true
  cleanupController:
    nodeSelector:
      team: devops
      service: devops-infra
      performance_type: standard
    image:
      registry: ghcr.io
    serviceMonitor:
      enabled: true
  reportsController:
    nodeSelector:
      team: devops
      service: devops-infra
      performance_type: standard
    image:
      registry: ghcr.io
    serviceMonitor:
      enabled: true