apiVersion: apps/v1
kind: Deployment
metadata:
  name: empty-api
  labels:
    app: empty-api
spec:
  selector:
    matchLabels:
      app: empty-api
  template:
    metadata:
      labels:
        app: empty-api
      annotations:
        instrumentation.opentelemetry.io/container-names: app
        instrumentation.opentelemetry.io/inject-java: 'true'
        kiali.io/dashboards: springboot-jvm,springboot-jvm-pool,springboot-tomcat
    spec:
      serviceAccountName: empty-api
      containers:
      - name: app
        image: empty-api
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: JAVA_TOOL_OPTIONS
          value: >
            -Xms2g -Xmx2g
            -Duser.timezone=Asia/Seoul
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        resources:
          limits:
            cpu: 500m
            memory: 2048Mi
          requests:
            cpu: 100m
            memory: 1024Mi