apiVersion: v1
kind: Service
metadata:
  name: empty-api
  labels:
    app: empty-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 9464
    targetPort: 9464
  selector:
    app: empty-api