cert-manager:
  global:
    leaderElection:
      namespace: provisioning
  image:
    repository: quay.io/jetstack/cert-manager-controller
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true
  webhook:
    image:
      repository: quay.io/jetstack/cert-manager-webhook
  cainjector:
    image:
      repository: quay.io/jetstack/cert-manager-cainjector
  startupapicheck:
    image:
      repository: quay.io/jetstack/cert-manager-ctl