apiVersion: v2
name: tempo
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: tempo-distributed
  version: 1.7.4
  repository: https://grafana.github.io/helm-charts