tempo-distributed:
  global:
    image:
      registry: docker.io
  gateway:
    enabled: true
  ingester:
    persistence:
      enabled: true
  metricsGenerator:
    enabled: true
  traces:
    zipkin:
      enabled: true
    otlp:
      http:
        enabled: true
      grpc:
        enabled: true
  reportingEnabled: false
  global_overrides:
    metrics_generator_processors:
    - service-graphs
    - span-metrics
  memcached:
    image:
      repository: library/memcached
  memcachedExporter:
    enabled: true
  metaMonitoring:
    serviceMonitor:
      enabled: true
  minio:
    enabled: false