apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: phlare-agent
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: phlare
    app.kubernetes.io/name: phlare
spec:
  endpoints:
  - port: http2
    relabelings:
    - action: replace
      replacement: observability/agent
      sourceLabels:
      - job
      targetLabel: job
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/component: agent
      app.kubernetes.io/instance: phlare
      app.kubernetes.io/name: phlare
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: phlare-distributor
  labels:
    app.kubernetes.io/component: distributor
    app.kubernetes.io/instance: phlare
    app.kubernetes.io/name: phlare
spec:
  endpoints:
  - port: http2
    relabelings:
    - action: replace
      replacement: observability/distributor
      sourceLabels:
      - job
      targetLabel: job
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/component: distributor
      app.kubernetes.io/instance: phlare
      app.kubernetes.io/name: phlare
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: phlare-ingester
  labels:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/instance: phlare
    app.kubernetes.io/name: phlare
spec:
  endpoints:
  - port: http2
    relabelings:
    - action: replace
      replacement: observability/ingester
      sourceLabels:
      - job
      targetLabel: job
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/component: ingester
      app.kubernetes.io/instance: phlare
      app.kubernetes.io/name: phlare
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: phlare-querier
  namespace: observability
  labels:
    app.kubernetes.io/component: querier
    app.kubernetes.io/instance: phlare
    app.kubernetes.io/name: phlare
spec:
  endpoints:
  - port: http2
    relabelings:
    - action: replace
      replacement: observability/querier
      sourceLabels:
      - job
      targetLabel: job
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/component: querier
      app.kubernetes.io/instance: phlare
      app.kubernetes.io/name: phlare
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: phlare-query-frontend
  namespace: observability
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: phlare
    app.kubernetes.io/name: phlare
spec:
  endpoints:
  - port: http2
    relabelings:
    - action: replace
      replacement: observability/query-frontend
      sourceLabels:
      - job
      targetLabel: job
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/component: query-frontend
      app.kubernetes.io/instance: phlare
      app.kubernetes.io/name: phlare
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: phlare-query-scheduler
  namespace: observability
  labels:
    app.kubernetes.io/component: query-scheduler
    app.kubernetes.io/instance: phlare
    app.kubernetes.io/name: phlare
spec:
  endpoints:
  - port: http2
    relabelings:
    - action: replace
      replacement: observability/query-scheduler
      sourceLabels:
      - job
      targetLabel: job
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/component: query-scheduler
      app.kubernetes.io/instance: phlare
      app.kubernetes.io/name: phlare