apiVersion: v2
name: karpenter
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: karpenter
  version: 0.16.0
  repository: https://charts.karpenter.sh