---
- name: Add anchore chart repo
  kubernetes.core.helm_repository:
    name: anchore
    repo_url: https://charts.anchore.io

- name: Install anchore-engine
  kubernetes.core.helm:
    name: anchore
    state: present
    chart_version: 1.22.1
    chart_ref: anchore/anchore-engine
    namespace: "{{ release_namespace }}"
    # create_namespace: true
    update_repo_cache: true
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    kube_context: "{{ cluster_arn }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  register: output

- debug:
    var: output