apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocdextension.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: development
  releaseName: argo-rollouts
  valuesFile: ./values.yaml