---
- name: Add gatekeeper chart repo
  kubernetes.core.helm_repository:
    name: gatekeeper
    repo_url: https://open-policy-agent.github.io/gatekeeper/charts

- name: Install gatekeeper
  kubernetes.core.helm:
    name: gatekeeper
    state: present
    chart_version: 3.7.1
    chart_ref: gatekeeper/gatekeeper
    namespace: "{{ release_namespace }}"
    # create_namespace: true
    update_repo_cache: true
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    kube_context: "{{ cluster_arn }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  register: output

- debug:
    var: output