apiVersion: v2
name: temporal
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: temporal
  version: 0.22.0
  repository: https://kwangil77.github.io/helm-charts