aws-ebs-csi-driver:
  image:
    repository: k8s.gcr.io/provider-aws/aws-ebs-csi-driver
  sidecars:
    provisioner:
      image:
        repository: k8s.gcr.io/sig-storage/csi-provisioner
    attacher:
      image:
        repository: k8s.gcr.io/sig-storage/csi-attacher
    snapshotter:
      image:
        repository: k8s.gcr.io/sig-storage/csi-snapshotter
    livenessProbe:
      image:
        repository: k8s.gcr.io/sig-storage/livenessprobe
    resizer:
      image:
        repository: k8s.gcr.io/sig-storage/csi-resizer
    nodeDriverRegistrar:
      image:
        repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
  node:
    tolerateAllTaints: true
  storageClasses:
  - name: gp3
    annotations:
      storageclass.kubernetes.io/is-default-class: 'true'
    parameters:
      fsType: ext4
      type: gp3
    reclaimPolicy: Delete
    allowVolumeExpansion: true