apiVersion: v1
kind: Service
metadata:
  name: empty-web
  labels:
    app: empty-web
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  - name: metrics
    port: 9464
    targetPort: 9464
  selector:
    app: empty-web