apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: istio-ingressgateway
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  addresses:
  - type: Hostname
    value: istio-ingressgateway.istio-system
  gatewayClassName: istio
  listeners:
  - name: istio-ingressgateway
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All