apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- probe.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: observability
  releaseName: prometheus-blackbox-exporter