apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: home
spec:
  interval: 30s
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
      - https://www.example.com