apiVersion: v1
kind: Service
metadata:
  name: promtail-headless
  labels:
    app: promtail
  annotations:
    prometheus.io/port: "3101"
    prometheus.io/scrape: "true"
spec:
  ports:
  - name: http-metrics
    port: 3101
    targetPort: http-metrics
    protocol: TCP
  selector:
    app: promtail
  clusterIP: None