apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- podmonitor.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: development
  releaseName: dependency-track
  valuesFile: ./values.yaml