apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
  labels:
    app: simple-server
  annotations:
    keel.sh/policy: force
    keel.sh/match-tag: 'true'
    keel.sh/pollSchedule: '@every 1m'
    keel.sh/trigger: poll
spec:
  selector:
    matchLabels:
      app: simple-server
  template:
    metadata:
      labels:
        app: simple-server
      annotations:
        sidecar.opentelemetry.io/inject: 'true'
    spec:
      serviceAccountName: simple
      containers:
      - name: app
        image: ghcr.io/kwangil77/simple-server
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: grpc
          containerPort: 9090
        env:
        - name: APP_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: APP_ENVIRONMENT
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['environment']
        - name: APP_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['service']
        - name: JAVA_TOOL_OPTIONS
          value: >
            -Xms4g -Xmx4g
            -Duser.timezone=Asia/Seoul
        - name: META_RELEASE
          value: $(APP_SERVICE)
        - name: SPRING_PROFILES_ACTIVE
          value: $(APP_ENVIRONMENT)
        - name: MANAGEMENT_METRICS_TAGS_ENVIRONMENT
          value: $(APP_ENVIRONMENT)
        - name: MANAGEMENT_TRACING_ENABLED
          value: 'true'
        envFrom:
        - secretRef:
            name: simple-server
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 4096Mi
          requests:
            cpu: 200m
            memory: 1024Mi
      nodeSelector:
        kubernetes.io/arch: amd64
        team: devops
        service: devops-service
        performance_type: standard
