apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-server
  labels:
    app: simple-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-server
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
