apiVersion: v1
kind: Secret
metadata:
  name: simple-server
  labels:
    app: simple-server
type: Opaque
stringData:
  SIMPLE_R2DBC_MASTER_PASSWORD: <path:kv/data/simple/simple/ds#password>
  SIMPLE_R2DBC_SLAVE_PASSWORD: <path:kv/data/simple/simple/ds#password>
