apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simple-api
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: simple-api
    template:
      metadata:
        labels:
          app: simple-api
      data:
        SIMPLE_DATASOURCE_MASTER_PASSWORD: "{{ .dsPassword }}"
        SIMPLE_DATASOURCE_SLAVE_PASSWORD: "{{ .dsPassword }}"
  data:
  - secretKey: dsPassword
    remoteRef:
      key: simple/simple/ds
      property: password
