apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- rollout.yaml
- secret.yaml
- servicemonitor.yaml
commonLabels:
  environment: dev
  service: simple-api
buildMetadata:
- managedByLabel
images:
- name: ghcr.io/kwangil77/simple-api
  newTag: latest
patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: simple-api
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 0
- target:
    group: autoscaling
    version: v2
    kind: HorizontalPodAutoscaler
    name: simple-api
  patch: |-
    - op: replace
      path: /spec/scaleTargetRef/apiVersion
      value: argoproj.io/v1alpha1
    - op: replace
      path: /spec/scaleTargetRef/kind
      value: Rollout
