apiVersion: v1
kind: Secret
metadata:
  name: simple-api
  labels:
    app: simple-api
type: Opaque
stringData:
  SIMPLE_DATASOURCE_MASTER_PASSWORD: <path:kv/data/simple/simple/ds#password>
  SIMPLE_DATASOURCE_SLAVE_PASSWORD: <path:kv/data/simple/simple/ds#password>
