---
- name: Add aws-ebs-csi-driver chart repo
  kubernetes.core.helm_repository:
    name: aws-ebs-csi-driver
    repo_url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver

- name: Install aws-ebs-csi-driver
  kubernetes.core.helm:
    name: aws-ebs-csi-driver
    state: present
    chart_version: 2.6.3
    chart_ref: aws-ebs-csi-driver/aws-ebs-csi-driver
    namespace: "{{ release_namespace }}"
    # create_namespace: true
    update_repo_cache: true
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    kube_context: "{{ cluster_arn }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  register: output
 
- debug:
    var: output