vault:
  injector:
    nodeSelector:
      team: devops
      service: devops-infra
      performance_type: standard
  server:
    nodeSelector:
      team: devops
      service: devops-infra
      performance_type: standard
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:...:certificate/...
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
        alb.ingress.kubernetes.io/tags: "Team=devops,Server=etc,Service=vault,Security_level=moderate,Environment=dev"
        alb.ingress.kubernetes.io/healthcheck-path: /v1/sys/health
        alb.ingress.kubernetes.io/security-groups: sg-...
        alb.ingress.kubernetes.io/ssl-redirect: '443'
        # nginx.ingress.kubernetes.io/ssl-redirect: 'true'
      hosts:
      - host: "vault.example.io"
        paths:
        - "/"
    service:
      type: NodePort
    standalone:
      enabled: false
    ha:
      enabled: true
      raft:
        enabled: true
        setNodeId: true
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
            telemetry {
              unauthenticated_metrics_access = true
            }
          }
          telemetry {
            prometheus_retention_time = "30s"
            disable_hostname = true
          }
          storage "raft" {
            path = "/vault/data"
          }
          seal "awskms" {
            region = "ap-northeast-2"
            kms_key_id = "arn:aws:kms:ap-northeast-2:..."
          }
          service_registration "kubernetes" {}