apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio
spec:
  profile: minimal
  hub: docker.io/istio
  tag: "1.21.0"
  components:
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          type: ClusterIP
  meshConfig:
    accessLogFile: "/dev/stdout"
    accessLogEncoding: JSON
    defaultProviders:
      metrics:
      - prometheus
    extensionProviders: 
    - name: opentelemetry
      opentelemetry:
        service: opentelemetry-collector.observability.svc.cluster.local
        port: 4317
    enableTracing: true
    trustDomain: cluster.local
    defaultConfig:
      holdApplicationUntilProxyStarts: true