apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: telemetry
spec:
  tracing:
  - providers:
    - name: opentelemetry
    customTags:
      environment:
        literal:
          value: local
    randomSamplingPercentage: 50