apiVersion: v2
name: aws-vpc-cni
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: aws-vpc-cni
  version: 1.1.14
  repository: https://aws.github.io/eks-charts