apiVersion: v2
name: argocd-image-updater
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: argocd-image-updater
  version: 0.9.3
  repository: https://argoproj.github.io/argo-helm