sonarqube:
  nodeSelector:
    kubernetes.io/arch: amd64
    team: devops
    service: devops-infra
    performance_type: memory
  tolerations:
  - key: performance_type
    operator: Equal
    value: mem
    effect: NoSchedule
  image:
    repository: docker.io/library/sonarqube
    tag: "10.2.1-community"
  initContainers:
    image: docker.io/library/busybox:1.36
  # extraInitContainers:
  # - name: install-plugins
  #   image: docker.io/library/alpine:3.8
  #   command:
  #   - "sh"
  #   - "-c"
  #   args:
  #   - |
  #     mkdir -p /opt/sonarqube/extensions/plugins
  #     wget -O /opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar https://....s3.ap-northeast-2.amazonaws.com/.../sonarqube-community-branch-plugin-1.14.0.jar
  #   volumeMounts:
  #   - mountPath: /opt/sonarqube/extensions
  #     name: sonarqube
  #     subPath: extensions
  initSysctl:
    image: docker.io/library/busybox:1.36
  initFs:
    image: docker.io/library/busybox:1.36
  prometheusExporter:
    enabled: true
    image: docker.io/curlimages/curl:8.2.0
  tests:
    enabled: false
  # jvmOpts: "-javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar=web"
  # jvmCeOpts: "-Xmx1024m -Xms256m -XX:+HeapDumpOnOutOfMemoryError -javaagent:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar=ce"
  jdbcOverwrite:
    enable: true
    jdbcUsername: sonar
  postgresql:
    enabled: false