apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: demo
    template:
      metadata:
        labels:
          app: demo
      data:
        AWS_ACCESS_KEY_ID: ''
        AWS_SECRET_ACCESS_KEY: ''