apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: demo
  labels:
    app: demo
    istio: ingressgateway
spec:
  parentRefs:
  - name: kubernetes-gateway
    namespace: istio-system
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: demo
      port: 8080