apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo
spec:
  propagators:
  - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.1"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.1.0
    env:
    - name: OTEL_METRICS_EXPORTER
      value: "prometheus"
    - name: OTEL_METRICS_EXEMPLAR_FILTER
      value: "trace_based"
    - name: OTEL_TRACES_EXPORTER
      value: "zipkin"
    - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
      value: "http://opentelemetry-collector.observability:9411/api/v2/spans"
    - name: OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_REQUEST_HEADERS
      value: "content-type"
    - name: OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_RESPONSE_HEADERS
      value: "content-type"