apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- externalsecret.yaml
- instrumentation.yaml
- servicemonitor.yaml
labels:
- includeSelectors: true
  pairs:
    environment: local
buildMetadata:
- managedByLabel
images:
- name: dev
  newTag: latest