apiVersion: v1
kind: Secret
metadata:
  name: backstage-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: <path:kv/data/backstage/postgresql#password>
  BITBUCKET_TOKEN: <path:kv/data/development/bitbucket#password>
  ARGOCD_AUTH_TOKEN: argocd.token=<path:kv/data/backstage/argocd#auth-token>
  SONARQUBE_TOKEN: <path:kv/data/development/sonarqube#token>
  VAULT_TOKEN: <path:kv/data/backstage/vault#token>
  GRAFANA_TOKEN: Bearer <path:kv/data/backstage/grafana#token>