apiVersion: v2
name: prometheus-node-exporter
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: prometheus-node-exporter
  version: 4.31.0
  repository: https://prometheus-community.github.io/helm-charts