---
- name: Add fluent chart repo
  kubernetes.core.helm_repository:
    name: fluent
    repo_url: https://fluent.github.io/helm-charts

- name: Install fluent-bit
  kubernetes.core.helm:
    name: fluent-bit
    state: present
    chart_version: 0.43.0
    chart_ref: fluent/fluent-bit
    namespace: "{{ release_namespace }}"
    # create_namespace: true
    update_repo_cache: true
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    kube_context: "{{ cluster_arn }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  register: output

- debug:
    var: output

# - name: Install servicemonitor
#   kubernetes.core.k8s:
#     kubeconfig: "{{ playbook_dir }}/inventory/config"
#     context: "{{ cluster_arn }}"
#     state: present
#     namespace: "{{ release_namespace }}"
#     definition: "{{ lookup('file', 'servicemonitor.yaml') }}"
#   register: output

# - debug:
#     var: output