apiVersion: v2
name: argo-events
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: argo-events
  version: 2.4.4
  repository: https://argoproj.github.io/argo-helm