apiVersion: v2
name: loki
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: loki-distributed
  version: 0.78.0
  repository: https://grafana.github.io/helm-charts