loki-distributed:
  gateway:
    image:
      registry: docker.io
  loki:
    image:
      registry: docker.io
  ingester:
    persistence:
      enabled: true
  queryScheduler:
    enabled: true
  ruler:
    enabled: true
    persistence:
      enabled: true
  compactor:
    enabled: true
    persistence:
      enabled: true
  indexGateway:
    enabled: true
    persistence:
      enabled: true
  memcached:
    image:
      registry: docker.io/library
  memcachedExporter:
    enabled: true
    image:
      registry: docker.io
  memcachedChunks:
    enabled: true
  memcachedFrontend:
    enabled: true
  memcachedIndexQueries:
    enabled: true
  memcachedIndexWrites:
    enabled: true
  serviceMonitor:
    enabled: true
