apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kiali
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kiali
    template:
      data:
        grafana-password: "{{ .adminPassword }}"
  data:
  - secretKey: adminPassword
    remoteRef:
      key: grafana/admin
      property: password