apiVersion: v2
name: phlare
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: phlare
  version: 0.5.3
  repository: https://grafana.github.io/helm-charts