apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: development
  releaseName: sourcegraph
  valuesFile: ./values.yaml