apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consul
  labels:
    app: consul
    component: server
spec:
  endpoints:
  - port: http
    path: /v1/agent/metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: consul
      component: server