mimir-distributed:
  image:
    repository: docker.io/grafana/mimir
  nginx:
    image:
      registry: docker.io
  memcached:
    image:
      repository: docker.io/library/memcached
  memcachedExporter:
    image:
      repository: docker.io/prom/memcached-exporter
  chunks-cache:
    enabled: true
  index-cache:
    enabled: true
  metadata-cache:
    enabled: true
  results-cache:
    enabled: true
  minio:
    enabled: false
  metaMonitoring:
    serviceMonitor:
      enabled: true