apiVersion: v2
name: litmus
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: litmus
  version: 3.1.0
  repository: https://litmuschaos.github.io/litmus-helm
- name: dex
  version: 0.15.3
  repository: https://charts.dexidp.io