apiVersion: v2
name: spring-cloud-dataflow
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: spring-cloud-dataflow
  version: 25.1.3
  repository: https://charts.bitnami.com/bitnami