apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  image: quay.io/prometheus/prometheus:v2.50.1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  exemplars: 
    maxSize: 100000
  enableFeatures:
  - exemplar-storage
  - native-histograms
  enableRemoteWriteReceiver: true
  prometheusExternalLabelName: ""
  replicaExternalLabelName: ""
  portName: http-web
  retention: 24h
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-prometheus
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  probeSelector: {}
  probeNamespaceSelector: {}
  ruleNamespaceSelector: {}
  ruleSelector: {}
  walCompression: true