apiVersion: monitoring.coreos.com/v1
kind: PrometheusAgent
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  shards: 1
  image: quay.io/prometheus/prometheus:v2.50.1
  prometheusExternalLabelName: ""
  replicaExternalLabelName: ""
  portName: http-web
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-prometheus
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  probeSelector: {}
  probeNamespaceSelector: {}
  remoteWrite:
  - url: "http://mimir-distributor.observability:8080/api/v1/push"
    sendExemplars: true
  walCompression: true