apiVersion: v2
name: grafana-oncall
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: oncall
  version: 1.3.55
  repository: https://grafana.github.io/helm-charts