---
- name: Add argo chart repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install argo-rollouts
  kubernetes.core.helm:
    name: argo-rollouts
    state: present
    chart_version: 2.34.1
    chart_ref: argo/argo-rollouts
    namespace: "{{ release_namespace }}"
    # create_namespace: true
    update_repo_cache: true
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    kube_context: "{{ cluster_arn }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  register: output

- debug:
    var: output

- name: Install argocdextension
  kubernetes.core.k8s:
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    context: "{{ cluster_arn }}"
    state: present
    namespace: "{{ release_namespace }}"
    definition: "{{ lookup('file', 'argocdextension.yaml') }}"
  register: output

- debug:
    var: output