apiVersion: v2
name: prometheus-statsd-exporter
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: prometheus-statsd-exporter
  version: 0.13.0
  repository: https://prometheus-community.github.io/helm-charts