apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector-metrics
  labels:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/name: opentelemetry-collector-metrics
spec:
  ports:
  - name: http-metrics
    protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: observability.opentelemetry
    app.kubernetes.io/managed-by: opentelemetry-operator
    app.kubernetes.io/part-of: opentelemetry