uptrace:
  service:
    type: NodePort 
  ingress:
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:...:certificate/...
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/tags: "Team=devops,Server=etc,Service=uptrace,Security_level=moderate,Environment=dev"
      alb.ingress.kubernetes.io/security-groups: sg-...
      alb.ingress.kubernetes.io/ssl-redirect: '443'
    hosts:
    - host: uptrace.example.io
      paths:
      - path: /
        pathType: Prefix
  uptrace:
    config:
      ch:
        addr: uptrace-clickhouse.observability:9000
        user: default
        password: <path:kv/data/uptrace/clickhouse#password>
        database: uptrace
        max_execution_time: 30s
      pg:
        addr: ....ap-northeast-2.rds.amazonaws.com:5432
        user: uptrace
        password: <path:kv/data/uptrace/postgresql#password>
        database: uptrace
      projects:
      - id: 1
        name: Uptrace
        token: 33251cd9e858a9e43d544d41f9e8b748
        pinned_attrs:
        - service.name
        - host.name
        - deployment.environment
        group_by_env: false
        group_funcs_by_service: false
      - id: 2
        name: Example
        token: c09f9fe5db686353a297f33e24a7446d
        pinned_attrs:
        - service.name
        - host.name
        - deployment.environment
        group_by_env: false
        group_funcs_by_service: false
      auth:
        oidc:
        - id: keycloak
          display_name: Keycloak
          issuer_url: https://keycloak.example.io/realms/master
          client_id: uptrace
          client_secret: <path:kv/data/uptrace/oidc#client-secret>
          scopes:
          - profile
          claim: email
      ch_schema:
        spans:
          ttl_delete: 7 DAY
        metrics:
          ttl_delete: 30 DAY
      site:
        addr: https://uptrace.example.io
clickhouse:
  auth:
    password: <path:kv/data/uptrace/clickhouse#password>
  shards: 1
  replicaCount: 1
  extraOverrides: |
    <clickhouse>
      <profiles>
        <default>
          <allow_experimental_window_functions>1</allow_experimental_window_functions>
          <allow_nondeterministic_mutations>1</allow_nondeterministic_mutations>
          <distributed_ddl_task_timeout>900</distributed_ddl_task_timeout>
        </default>
      </profiles>
      <remote_servers>
        <cluster>
          <shard>
            <replica>
              <host>uptrace-clickhouse-shard0-0.uptrace-clickhouse-headless.observability.svc.cluster.local</host>
              <port>9000</port>
            </replica>
          </shard>
        </cluster>
      </remote_servers>
      <storage_configuration>
        <disks>
          <default>
            <keep_free_space_bytes>10485760</keep_free_space_bytes>
          </default>
          <s3>
            <type>s3</type>
            <endpoint>http://minio-hl.management:9000/example-dev-uptrace-bucket//</endpoint>
            <access_key_id><path:kv/data/minio/secret#access-key></access_key_id>
            <secret_access_key><path:kv/data/minio/secret#secret-key></secret_access_key>
          </s3>
        </disks>
        <policies>
          <tiered>
            <volumes>
              <default>
                <disk>default</disk>
              </default>
              <s3>
                <disk>s3</disk>
                <perform_ttl_move_on_insert>0</perform_ttl_move_on_insert>
              </s3>
            </volumes>
          </tiered>
        </policies>
      </storage_configuration>
    </clickhouse>
  persistence:
    size: 50Gi