apiVersion: v2
name: metrics-server
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: metrics-server
  version: 3.12.0
  repository: https://kubernetes-sigs.github.io/metrics-server