apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- servicemonitor.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: observability
  releaseName: fluent-bit
  valuesFile: ./values.yaml