fluent-bit:
  config:
    service: |
      [SERVICE]
          daemon off
          flush {{ .Values.flush }}
          log_level {{ .Values.logLevel }}
          parsers_file parsers.conf
          parsers_file custom_parsers.conf
          http_server on
          http_listen 0.0.0.0
          http_port {{ .Values.metricsPort }}
          health_check on
          storage.path /var/log/flb-storage/
          storage.sync normal
          storage.checksum off
          storage.backlog.mem_limit 5M
    inputs: |
      [INPUT]
          name tail
          storage.type filesystem
          path /var/log/containers/*.log
          multiline.parser docker, cri
          tag kube.*
          mem_buf_limit 5MB
          skip_long_lines on
          threaded on
    outputs: |
      [OUTPUT]
          name loki
          match kube.*
          storage.total_limit_size 5M
          host loki-distributor.observability
          port 3100
          # tls on
          # tls.verify on
          labels cluster=example-dev, namespace=$kubernetes['namespace_name'], node_name=$kubernetes['host'], pod=$kubernetes['pod_name'], container=$kubernetes['container_name']
          auto_kubernetes_labels on