apiVersion: v1
kind: ConfigMap
metadata:
  name: empty-php
data:
  default.conf: |
    server {
        listen       80;
        server_name  _;

        location / {
            try_files $uri $uri/ /index.php$request_uri;
        }
        error_page   500 502 503 504  /50x.html;

        location = /50x.html {
            root   /usr/share/nginx/html;
        }
        location ~ \.php$ {
            root   /var/www/html;
            fastcgi_pass   127.0.0.1:9000;
            include fastcgi.conf;
        }
    }