apiVersion: v2
name: kafka-ui
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: kafka-ui
  version: 0.7.5
  repository: https://provectus.github.io/kafka-ui-charts