apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER=<path:kv/data/minio/secret#access-key>
    export MINIO_ROOT_PASSWORD=<path:kv/data/minio/secret#secret-key>