apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
      annotations:
        instrumentation.opentelemetry.io/container-names: app
        nstrumentation.opentelemetry.io/inject-java: 'true'
        kiali.io/dashboards: springboot-jvm,springboot-jvm-pool,springboot-tomcat
    spec:
      serviceAccountName: demo
      containers:
      - name: app
        image: demo
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: AWS_REGION
          value: ap-northeast-2
        - name: JAVA_TOOL_OPTIONS
          value: >
            -Xms4g -Xmx4g
            -Duser.timezone=Asia/Seoul
        # - name: AWS_IAM_USER_ACCESSKEY_ELAPSEDHOURS
        #   value: '15000'
        envFrom:
        - secretRef:
            name: demo
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 4096Mi
          requests:
            cpu: 200m
            memory: 1024Mi