apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  # - name: metrics
  #   port: 9464
  #   targetPort: 9464
  selector:
    app: demo