apiVersion: v2
name: grafana-agent
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: grafana-agent
  version: 0.30.0
  repository: https://grafana.github.io/helm-charts