apiVersion: apps/v1
kind: Deployment
metadata:
  name: empty-php
  labels:
    app: empty-php
spec:
  selector:
    matchLabels:
      app: empty-php
  template:
    metadata:
      labels:
        app: empty-php
    spec:
      serviceAccountName: empty-php
      containers:
      - name: app
        image: empty-php
        imagePullPolicy: Never
        ports:
        - name: php-fpm
          containerPort: 9000
        env:
        - name: DD_ENV
          value: "local"
        - name: DD_SERVICE
          value: "empty-php"
        - name: DD_VERSION
          value: "0.0.1"
        - name: DD_AGENT_HOST
          value: "opentelemetry-collector.observability"
        - name: DD_TRACE_OTEL_ENABLED
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 9000
        readinessProbe:
          tcpSocket:
            port: 9000
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
      - name: proxy
        image: docker.io/library/nginx:1.23.1-alpine
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: empty-php
          mountPath: /etc/nginx/conf.d/
          readOnly: true
        livenessProbe:
          httpGet:
            path: /nginx_status
            port: 80
        readinessProbe:
          httpGet:
            path: /nginx_status
            port: 80
        resources:
          limits:
            cpu: 20m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
      volumes:
      - name: empty-php
        configMap:
          name: empty-php