---
# - name: Create namespace
#   kubernetes.core.k8s:
#     kubeconfig: "{{ playbook_dir }}/inventory/config"
#     context: "{{ cluster_arn }}"
#     name: "{{ release_namespace }}"
#     api_version: v1
#     kind: Namespace
#     state: present
#   register: output

# - debug:
#     var: output

- name: Install configmap
  kubernetes.core.k8s:
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    context: "{{ cluster_arn }}"
    state: present
    namespace: "{{ release_namespace }}"
    definition: "{{ lookup('file', 'configmap.yaml') }}"
  register: output
  tags:
    - m3

- debug:
    var: output
  tags:
    - m3

- name: Add prometheus-community chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Install prometheus
  kubernetes.core.helm:
    name: prometheus
    state: present
    chart_version: 15.9.0
    chart_ref: prometheus-community/prometheus
    namespace: "{{ release_namespace }}"
    # create_namespace: true
    update_repo_cache: true
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    kube_context: "{{ cluster_arn }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  register: output

- debug:
    var: output

- name: Install service
  kubernetes.core.k8s:
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    context: "{{ cluster_arn }}"
    state: present
    namespace: "{{ release_namespace }}"
    definition: "{{ lookup('template', 'service.yaml.j2') }}"
  register: output
  tags:
    - thanos

- debug:
    var: output
  tags:
    - thanos