apiVersion: v2
name: argo-workflows
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: argo-workflows
  version: 0.39.9
  repository: https://argoproj.github.io/argo-helm