vault:
  global:
    serverTelemetry:
      prometheusOperator: true
  injector:
    metrics:
      enabled: true
    image:
      repository: "docker.io/hashicorp/vault-k8s"
      tag: "1.4.0"
    agentImage:
      repository: "docker.io/hashicorp/vault"
      tag: "1.15.6"
  server:
    image:
      repository: "docker.io/hashicorp/vault"
      tag: "1.15.6"
  csi:
    enabled: true
    image:
      repository: "docker.io/hashicorp/vault-csi-provider"
      tag: "1.4.1"