apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/aws/eks-charts/master/stable/aws-load-balancer-controller/crds/crds.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: kube-system
  releaseName: aws-load-balancer-controller
  valuesFile: ./values.yaml