---
- name: Install appmesh
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    release_namespace: management
  gather_facts: no

  pre_tasks:
    - name: Prepare namespace
      import_tasks: namespace.yaml

  roles:
    - appmesh-controller
    - appmesh-gateway