---
- name: Install argocd
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    release_namespace: development
  gather_facts: no

  pre_tasks:
    - name: Prepare namespace
      import_tasks: namespace.yaml

  roles:
    - argocd
    # - argocd-image-updater