---
- name: Install base
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    release_namespace: kube-system
  gather_facts: no

  roles:
    # - aws-vpc-cni
    - aws-ebs-csi-driver
    # - karpenter
    - cluster-autoscaler
    - aws-load-balancer-controller
    - external-dns
    - secrets-store-csi-driver