---
- name: Install istio
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    release_namespace: istio-system
  gather_facts: no

  pre_tasks:
    - name: Prepare namespace
      import_tasks: namespace.yaml

  roles:
    - istio-base
    - istiod
    - istio-gateway
    # - kiali
    - kiali-operator