operator:
  operator:
    nodeSelector:
      team: devops
      service: devops-infra
      performance_type: standard
    image:
      repository: docker.io/minio/operator
    env:
    - name: MINIO_OPERATOR_TLS_ENABLE
      value: "off"
    - name: MINIO_CONSOLE_TLS_ENABLE
      value: "off"
    - name: CLUSTER_DOMAIN
      value: "cluster.local"
    - name: WATCHED_NAMESPACE
      value: ""
  console:
    nodeSelector:
      team: devops
      service: devops-infra
      performance_type: standard
    image:
      repository: docker.io/minio/operator