apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- vmcluster.yaml
- vmalert.yaml
- vmagent.yaml
configMapGenerator:
- name: vmalert
  files:
  - ./files/alerts.yaml
  - ./files/rules.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: vmalert
