apiVersion: monitoring.coreos.com/v1
kind: PrometheusAgent
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  nodeSelector:
    team: devops
    service: devops-infra
    performance_type: memory
  tolerations:
  - key: performance_type
    operator: Equal
    value: mem
    effect: NoSchedule
  replicas: 2
  shards: 2
  image: quay.io/prometheus/prometheus:v2.50.1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  enableFeatures:
  - exemplar-storage
  - native-histograms
  enableRemoteWriteReceiver: true
  prometheusExternalLabelName: ""
  replicaExternalLabelName: ""
  portName: http-web
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-prometheus
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  probeSelector: {}
  probeNamespaceSelector: {}
  remoteWrite:
  - url: "http://mimir-gateway.observability/api/v1/push"
    sendExemplars: true
  walCompression: true