apiVersion: v1
kind: Secret
metadata:
  name: prometheus
  labels:
    app: prometheus
type: Opaque
stringData:
  scrape.yml: ''
  alertmanager.yaml: |
    - static_configs:
      - targets:
        - alertmanager.observability:9093
---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager
  labels:
    app: alertmanager
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 1m
      slack_api_url: <path:kv/data/alertmanager/slack#api-url>
    route:
      receiver: slack-notifications
      group_by:
      - alertname
      - app
    receivers:
    - name: slack-notifications
      slack_configs:
      - channel: "#devops_alert"
        username: alertmanager
        icon_emoji: ":prometheus:"
        send_resolved: true