apiVersion: v2
name: prometheus
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: kube-prometheus-stack
  version: 57.1.1
  repository: https://prometheus-community.github.io/helm-charts