kube-prometheus-stack:
  fullnameOverride: prometheus
  defaultRules:
    rules:
      kubeControllerManager: false
      kubeSchedulerAlerting: false
      kubeSchedulerRecording: false
  prometheusOperator:
    admissionWebhooks:
      patch:
        image:
          registry: k8s.gcr.io
    image:
      registry: quay.io
    prometheusConfigReloader:
      image:
        registry: quay.io
    thanosImage:
      registry: quay.io
  alertmanager:
    enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  kubelet:
    serviceMonitor:
      metricRelabelings:
      - action: replace
        sourceLabels:
        - node
        targetLabel: instance