apiVersion: v1
kind: Secret
metadata:
  name: awx-secret-key
type: Opaque
stringData:
  secret_key: awxsecret
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
type: Opaque
stringData:
  password: <path:kv/data/awx/admin#password>
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
type: Opaque
stringData:
  host: ....ap-northeast-2.rds.amazonaws.com
  port: "5432"
  database: awx
  username: awx
  password: <path:kv/data/awx/postgresql#password>