apiVersion: v2
name: sourcegraph
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: sourcegraph
  version: 0.0.1
  repository: https://kwangil77.github.io/helm-charts