apiVersion: v2
name: argo-cd
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: argo-cd
  version: 6.7.2
  repository: https://argoproj.github.io/argo-helm