argo-cd:
  fullnameOverride: argocd
  global:
    image:
      repository: quay.io/argoproj/argocd
      tag: "v2.10.3"
  controller:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  server:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    extensions:
      enabled: true
      image:
        repository: "ghcr.io/argoproj-labs/argocd-extensions"
  repoServer:
    serviceAccount:
      create: true
      name: argocd-repo-server
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  applicationSet:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  notifications:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true