kube-prometheus-stack:
  defaultRules:
    rules:
      kubeControllerManager: false
      kubeSchedulerAlerting: false
      kubeSchedulerRecording: false
  prometheusOperator:
    nodeSelector:
      team: devops
      service: devops-infra
      performance_type: memory
    tolerations:
    - key: performance_type
      operator: Equal
      value: mem
      effect: NoSchedule