apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: telegraf
  labels:
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/instance: telegraf
spec:
  endpoints:
  - port: prometheus-client
    honorLabels: true
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: telegraf
      app.kubernetes.io/instance: telegraf