apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- jaeger.yaml
- secret.yaml
- podmonitor.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: observability
  releaseName: jaeger-clickhouse
  valuesFile: ./values.yaml