apiVersion: v1
kind: Secret
metadata:
  name: jaeger-clickhouse-secret
type: Opaque
stringData:
  config.yaml: |
    address: jaeger-clickhouse.observability:9000
    init_sql_scripts_dir:
    init_tables:
    max_span_count:
    batch_write_size:
    batch_flush_interval:
    encoding:
    ca_file:
    username:
    password: <path:kv/data/jaeger/clickhouse#password>
    database:
    tenant:
    metrics_endpoint: localhost:9090
    replication:
    spans_table:
    spans_index_table:
    operations_table:
    ttl:
    max_num_spans: