---
- name: Add eks chart repo
  kubernetes.core.helm_repository:
    name: eks
    repo_url: https://aws.github.io/eks-charts

- name: Install appmesh-controller
  kubernetes.core.helm:
    name: appmesh-controller
    state: present
    chart_version: 1.4.4
    chart_ref: eks/appmesh-controller
    namespace: "{{ release_namespace }}"
    # create_namespace: true
    update_repo_cache: true
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    kube_context: "{{ cluster_arn }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  register: output

- debug:
    var: output 