{
 "title": "SonarQube",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": {
     "query": "{container=\"sonarqube\"}"
    }
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "up{container=\"sonarqube\", namespace=\"$Namespace\", endpoint=\"http\"}"
    }
   },
   {
    "name": "Pod",
    "query": {
     "query": "{container=\"sonarqube\", instance=\"$Node\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SonarQube ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$Node\"}",
     "legendFormat": "SonarQube"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_health_compute_engine_status{instance=\"$Node\"}",
     "legendFormat": "CE Health $Node"
    },
    {
     "expr": "sonarqube_health_elasticsearch_status{instance=\"$Node\"}",
     "legendFormat": "ES Health $Node"
    },
    {
     "expr": "sonarqube_health_web_status{instance=\"$Node\"}",
     "legendFormat": "Web Health $Node"
    }
   ]
  },
  {
   "title": "DevOps Platform Config",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_health_integration_gitlab_status{instance=\"$Node\"}",
     "legendFormat": "GitLab"
    },
    {
     "expr": "sonarqube_health_integration_azuredevops_status{instance=\"$Node\"}",
     "legendFormat": "Azure"
    },
    {
     "expr": "sonarqube_health_integration_github_status{instance=\"$Node\"}",
     "legendFormat": "GitHub"
    },
    {
     "expr": "sonarqube_health_integration_bitbucket_status{instance=\"$Node\"}",
     "legendFormat": "Bitbucket"
    }
   ]
  },
  { "title": "License", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "License",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sonarqube_license_days_before_expiration_total)",
     "legendFormat": "License Expires in  "
    }
   ]
  },
  {
   "title": "License LoC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "max(sonarqube_license_number_of_lines_analyzed_total)",
     "legendFormat": "LoC Analyzed"
    },
    {
     "expr": "max(sonarqube_license_number_of_lines_remaining_total)",
     "legendFormat": "LoC Volume"
    }
   ]
  },
  { "title": "Compute Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sonarqube_health_compute_engine_status{instance=\"$Node\"}"
    }
   ]
  },
  {
   "title": "CE Task Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sonarqube_compute_engine_pending_tasks_total{instance=\"$Node\"}",
     "legendFormat": "Queue"
    },
    {
     "expr": "SonarQube_ComputeEngineTasks_ErrorCount{pod=\"$Pod\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "SonarQube_ComputeEngineTasks_InProgressCount{pod=\"$Pod\"}",
     "legendFormat": "In Progress"
    }
   ]
  },
  {
   "title": "CE Tasks running duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "avg(sonarqube_compute_engine_tasks_running_duration_seconds_count{instance=\"$Node\", task_type=\"REPORT\"})",
     "legendFormat": "Reports"
    },
    {
     "expr": "avg(sonarqube_compute_engine_tasks_running_duration_seconds_count{instance=\"$Node\", task_type=\"VIEW_REFRESH\"})",
     "legendFormat": "View Refreshes"
    },
    {
     "expr": "avg(sonarqube_compute_engine_tasks_running_duration_seconds_count{instance=\"$Node\", task_type=\"APP_REFRESH\"})",
     "legendFormat": "App Refreshes"
    }
   ]
  },
  { "title": "Base Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$Namespace\", pod=\"$Pod\"}) by (pod)",
     "legendFormat": "$Node Usage"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$Namespace\",resource=\"cpu\", pod=\"$Pod\"}",
     "legendFormat": "$Node Request"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$Namespace\",resource=\"cpu\", pod=\"$Pod\"}",
     "legendFormat": "$Node Limit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$Namespace\", pod=\"$Pod\"}) by (pod)",
     "legendFormat": "$Node usage"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$Namespace\",resource=\"memory\", pod=\"$Pod\"}",
     "legendFormat": "$Node request"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$Namespace\",resource=\"memory\", pod=\"$Pod\"}",
     "legendFormat": "$Node limit"
    }
   ]
  },
  {
   "title": "Database Connectivity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "SonarQube_Database_PoolActiveConnections{pod=\"$Pod\"}",
     "legendFormat": "App Database Connections"
    },
    {
     "expr": "SonarQube_ComputeEngineDatabaseConnection_PoolActiveConnections{pod=\"$Pod\"}",
     "legendFormat": "CE Database Connections"
    }
   ]
  }
 ]
}