prometheus-pushgateway:
  nodeSelector:
    team: devops
    service: devops-infra
    performance_type: standard
  image:
    repository: docker.io/prom/pushgateway
  persistentVolume:
    enabled: true
  serviceMonitor:
    enabled: true
    namespace: ""