atlantis:
  orgAllowlist: 'bitbucket.example.io/scm/tc/simple*'
  bitbucket:
    user: devops
    token: <path:kv/data/development/bitbucket#password>
    secret: <path:kv/data/atlantis/bitbucket#secret>
    baseURL: https://bitbucket.example.io
  ingress:
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:...:certificate/...
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/tags: "Team=devops,Server=etc,Service=atlantis,Security_level=moderate,Environment=dev"
      alb.ingress.kubernetes.io/healthcheck-path: /healthz
      alb.ingress.kubernetes.io/security-groups: sg-...
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      # nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    path: /
    pathType: Prefix
    host: atlantis.example.io
  extraVolumes:
  - name: aws-volume
    configMap:
      name: aws-config
  extraVolumeMounts:
  - name: aws-volume
    readOnly: true
    mountPath: /home/atlantis/.aws
  redis:
    host: ....cache.amazonaws.com
    db: '6'