kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-agent-extra
subjects:
- kind: ServiceAccount
  name: grafana-agent
  namespace: observability
roleRef:
  kind: ClusterRole
  name: grafana-agent-extra
  apiGroup: rbac.authorization.k8s.io