apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: observability
  releaseName: grafana-agent
  valuesFile: ./values.yaml