apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1
dependencies:
- name: grafana
  version: 7.0.3
  repository: https://grafana.github.io/helm-charts