grafana:
  global:
    image:
      registry: docker.io
  image:
    tag: "10.4.0"
  grafana.ini:
    remote_cache:
      type: redis
    auth:
      sigv4_auth_enabled: true
    unified_alerting:
      enabled: true
    alerting:
      enabled: false
    feature_toggles:
      traceToMetrics: true
  imageRenderer:
    enabled: true