---
- name: Add vector chart repo
  kubernetes.core.helm_repository:
    name: vector
    repo_url: https://helm.vector.dev

- name: Install vector
  kubernetes.core.helm:
    name: vector
    state: present
    chart_version: 0.30.2
    chart_ref: vector/vector
    namespace: "{{ release_namespace }}"
    # create_namespace: true
    update_repo_cache: true
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    kube_context: "{{ cluster_arn }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  register: output

- debug:
    var: output