apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflows-view
subjects:
- kind: ServiceAccount
  name: argo-workflows-view
  namespace: development
roleRef:
  kind: ClusterRole
  name: argo-workflows-view
  apiGroup: rbac.authorization.k8s.io