apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-postgres
type: Opaque
stringData:
  username: argo
  password: <path:kv/data/argo-workflows/postgresql#password>
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-sso
type: Opaque
stringData:
  client-id: argo-workflows
  client-secret: <path:kv/data/argo-workflows/oidc#client-secret>
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-minio
type: Opaque
stringData:
  accesskey: <path:kv/data/minio/secret#access-key>
  secretkey: <path:kv/data/minio/secret#secret-key>