template_files: {}
alertmanager_config: |
  global:
    resolve_timeout: 1m
    slack_api_url: "{{ slack_url }}"
  route:
    receiver: slack-notifications
    group_by:
    - alertname
    - app
  receivers:
  - name: slack-notifications
    slack_configs:
    - channel: "{{ slack_channel }}"
      send_resolved: true
      username: alertmanager
      icon_emoji: ":prometheus:"