---
- name: Add external-dns chart repo
  kubernetes.core.helm_repository:
    name: external-dns
    repo_url: https://kubernetes-sigs.github.io/external-dns

- name: Install external-dns
  kubernetes.core.helm:
    name: external-dns
    state: present
    chart_version: 1.7.1
    chart_ref: external-dns/external-dns
    namespace: "{{ release_namespace }}"
    # create_namespace: true
    update_repo_cache: true
    kubeconfig: "{{ playbook_dir }}/inventory/config"
    kube_context: "{{ cluster_arn }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
  register: output

- debug:
    var: output