opentelemetry-operator:
  manager:
    image:
      repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
      tag: v0.96.0
    collectorImage:
      repository: docker.io/otel/opentelemetry-collector-contrib
      tag: "0.96.0"
    serviceMonitor:
      enabled: true
  kubeRBACProxy:
    image:
      repository: quay.io/brancz/kube-rbac-proxy
      tag: v0.15.0
  testFramework:
    image:
      repository: docker.io/library/busybox