apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: thanos-ruler-configmap
  files:
  - ./files/thanos-alerts.yml
  - ./files/thanos-rules.yml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app: thanos
helmGlobals:
  chartHome: ../
helmCharts:
- name: base
  namespace: observability
  releaseName: thanos
  valuesFile: ./values.yaml