thanos:
  objstoreConfig: |
    type: S3
    config:
      bucket: example-dev-thanos-bucket
      endpoint: minio-hl.management:9000
      access_key: <path:kv/data/minio/secret#access-key>
      secret_key: <path:kv/data/minio/secret#secret-key>
      insecure: true
      signature_version2: false
      # endpoint: "s3.amazonaws.com"
      # region: ap-northeast-2
  indexCacheConfig: |
    type: MEMCACHED
    config:
      addresses:
      - dns+thanos-memcached-index.observability.svc:11211
      timeout: 500ms
      max_idle_connections: 100
      max_item_size: 1MiB
      max_async_concurrency: 10
      max_async_buffer_size: 10000
      max_get_multi_concurrency: 100
      max_get_multi_batch_size: 0
      dns_provider_update_interval: 10s
      expiration: 24h
  bucketCacheConfig: |
    type: MEMCACHED
    config:
      addresses:
      - dns+thanos-memcached-bucket.observability.svc:11211
      timeout: 500ms
      max_idle_connections: 100
      max_item_size: 1MiB
      max_async_concurrency: 20
      max_async_buffer_size: 10000
      max_get_multi_concurrency: 100
      max_get_multi_batch_size: 0
      dns_provider_update_interval: 10s
    chunk_subrange_size: 16000
    max_chunks_get_range_requests: 3
    chunk_object_attrs_ttl: 24h
    chunk_subrange_ttl: 24h
    blocks_iter_ttl: 5m
    metafile_exists_ttl: 2h
    metafile_doesnt_exist_ttl: 15m
    metafile_content_ttl: 24h
    metafile_max_size: 1MiB
  queryFrontend:
    config: |
      type: MEMCACHED
      config:
        addresses:
        - dns+thanos-memcached-frontend.observability.svc:11211
        timeout: 500ms
        max_idle_connections: 100
        max_item_size: 1MiB
        max_async_concurrency: 10
        max_async_buffer_size: 10000
        max_get_multi_concurrency: 100
        max_get_multi_batch_size: 0
        dns_provider_update_interval: 10s
        expiration: 24h
  compactor:
    persistence:
      size: 50Gi
  ruler:
    alertmanagers:
    - "http://alertmanager.observability:9093"
    existingConfigmap: thanos-ruler-configmap
  receive:
    tsdbRetention: 7d
    persistence:
      size: 50Gi